---
name: Checks

on:
  push:
    branches: 
      - "*"
    tags: 
      - "v[0-9]+.[0-9]+.[0-9]+*"

jobs:
  test-image:
    name: Type checking, linting, tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.REPO_TOKEN }}
          submodules: true

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: |
            3.11
            3.10
            3.9
            3.8

      - name: Install python dependencies
        run: pip install -r requirements/dev.txt

      - name: Run type checking
        run: make mypy

      - name: Run linting
        run: make lint

      - name: Run tests
        run: make test
