---
name: Release

on:
  push:
    tags: 
      - "v[0-9]+.[0-9]+.[0-9]+*"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.REPO_TOKEN }}
          submodules: true

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install python dependencies
        run: pip install ".[ci]" 

      - name: Build changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v3
        with:
          commitMode: true
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}

      - name: Make build
        run: hatch build

      - name: Publish
        run: hatch publish -r main -u __token__ -a ${{ secrets.PYPI }}

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.REPO_TOKEN }}
          body: ${{ steps.github_release.outputs.changelog }}
