---
name: Release

on:
  push:
    tags: 
      - "v[0-9]+.[0-9]+.[0-9]+*"

jobs:
  test-image:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.REPO_TOKEN }}
          submodules: true

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install python dependencies
        run: pip install ".[ci]" 

      # - name: Build changelog
      #   id: changelog
      #   uses: mikepenz/release-changelog-builder-action@v3
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
      #
      # - name: Output changelog
      #   run: echo ${{ steps.changelog.outputs.changelog }}

      - name: Make build
        run: hatch build

      - name: Publish
        run: hatch publish -r main -u __token__ -a ${{ secrets.PYPI }}
